###########################
# Cluster IP Service
###########################
kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  type: NodePort
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32000
---
###########################
# Persistent Volume Claim
###########################
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  #labels:
     #type: local
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M
 # volumeName: postgres-pv