name: pipeline

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

  publish:
      runs-on: ubuntu-latest
      needs: build		  

  test:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Teste
      run: 
          python -m pip install --upgrade pip
          pip debug -r app/project/requirements.txt
